shanghaidazhong_7<-as.vector(read.csv("C:/Users/Administrator/Desktop/Baidu/No.7上汽.csv",header=F))
cor(shanghaidazhong_4,salesvolume)
tuguan_2<-as.vector(read.csv("C:/Users/Administrator/Desktop/Baidu/No.a2途锐.csv",header=F))
cor(tuguan_2,salesvolume)
salesvolume2<-as.vector(read.csv("C:/Users/Administrator/Desktop/argo/数据/大众汽车销量滞后2.csv",header=F))
shanghaidazhong_1<-as.matrix(read.csv("C:/Users/Administrator/Desktop/Baidu all/No.1上海大众.csv",header=F))
shanghaidazhong_2<-as.matrix(read.csv("C:/Users/Administrator/Desktop/Baidu all/No.2一汽.csv",header=F))
shanghaidazhong_3<-as.matrix(read.csv("C:/Users/Administrator/Desktop/Baidu all/No.3一汽大众.csv",header=F))
shanghaidazhong_4<-as.matrix(read.csv("C:/Users/Administrator/Desktop/Baidu all/No.4上海大众汽车报价.csv",header=F))
passate<-as.matrix(read.csv("C:/Users/Administrator/Desktop/Baidu all/帕萨特.csv",header=F))